disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace # explicitly disabled
  - line_length
  - force_cast
  - valid_docs
  - force_try
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  
type_body_length:
  warning: 500
  error: 1000
  
variable_name:
  excluded: # excluded via string array
    - id
    - in
    - at
    - to
    - no
    - na
file_length:
  warning: 500
  error: 1000
